version: '3.9'
services:

  app:
    container_name: home-library_app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    image: yuliyanarkevich/home-library_app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - ${NETWORK_NAME}


  postgres:
    container_name: postgres_db
    build: 
      dockerfile: ./src/db/Dockerfile
    image: yuliyanarkevich/home-library_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports: 
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - ${NETWORK_NAME}
    
networks:
  library-service:
    name: ${NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '172.16.0.0/24'
          gateway: '172.16.0.1'


volumes:
  app:
  postgres: