# Файл docker-compose должен начинаться с тега версии.
version: '3.9'
# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.
services:

  app:
    container_name: home-library_app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    image: app-image
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}


  postgres:
    container_name: postgres_db
    build: 
      dockerfile: ./src/db/Dockerfile
    image: db-image
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports: 
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    



volumes:
  app:
  postgres: